export const panels = [
  {
    title: "Galleries",
    url: "galleryurl",
    blog: "Galleries",
    template: "panel1",
  },
  {
    title: "Archive photos",
    url: "galleryurl",
    blog: "Australia",
    template: "panel2",
  },
  {
    title: "All photos",
    url: "galleryurl",
    blog: "Business",
    template: "panel1",
  },
];

panels.forEach((panel) => {
  panel.feed = [
    {
      id: 7,
      date: "25th February 2019",
      publishDate: "Sep 11 2023",
      title: "cats and lego and a mouse and things",
      content: "Cats and dogs living together",
      editUrl: "editurl",
      isPinned: 1,
      pinnedAt: 2,
      images: [
        {
          id: "j49fj3ffsdafsdgsdsgdf8rj",
          guid: "fadsffhgfghg",
          type: "jpeg",
          title: "Plant",
          width: "509",
          height: "1200",
          fileSize: "1024",
          caption:
            "Vivamus at vesti , tempus eges bulum ante, ac dapibus velit. In tristique est ac dui ornare, tempus egesmauris blandit.  so that i can see it's wokring and then celebrate a job well done",
          url:
            "https://res.cloudinary.com/cognitives/image/upload/ljmveksnjas1tiqywvtl",
          createdDate: "Sep 12 2023",
        },
        {
          id: "j49fj3fgsdsgdf8rj",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Cat",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption:
            "Vivamus at vesti , tempus eges bulum ante, ac dapibus velit. In tristique est ac dui ornare, tempus egesmauris blandit.  so that i can see it's wokring and then celebrate a job well done",
          url: "https://i.ytimg.com/vi/EuvTORWs244/maxresdefault.jpg",
          createdDate: "Sep 11 2023",
        },
        {
          id: "lkiuygfyny66",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Lego",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption:
            "Vivamus at vesti , tempus eges bulum ante, ac dapibus velit. In tristique est ac dui ornare, tempus egesmauris blandit. ",
          url:
            "https://weburbanist.com/wp-content/uploads/2008/10/lego_art_1.jpg",
          createdDate: "Sep 11 2023",
        },
        {
          id: "mjghjligm",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Guitar!",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption:
            "Vivamus at vesti , tempus eges bulum ante, ac dapibus velit. In tristique est ac dui ornare, tempus egesmauris blandit. ",
          url: "https://www.geekalerts.com/u/lego-guitar.jpg",
          createdDate: "Sep 11 2023",
        },
      ],
    },
    {
      id: 8,
      title: "Prince doing singing and dancing very well thank you very much",
      date: "25th April 2010",
      publishDate: "Sep 11 2023",
      content: "Cats and dogs living together",
      editUrl: "editurl",
      isPinned: 0,
      pinnedAt: 0,
      images: [
        {
          id: "6e5hfdghs5dt",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Prince One",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption:
            "Vivamus at vesti , tempus eges bulum ante, ac dapibus velit. In tristique est ac dui ornare, tempus egesmauris blandit. ",
          url:
            "https://static.guim.co.uk/sys-images/Music/Pix/pictures/2011/6/3/1307115506503/Prince-performing-on-stag-007.jpg",
        },
        {
          id: "jkjjfddswyj",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Prince Two",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption: "What's he been up to all these years",
          url:
            "http://4.bp.blogspot.com/-lqsQusSni-Q/TnvzRGHOH_I/AAAAAAAAARg/sYebBSwumX4/w1200-h630-p-k-nu/prince-hohner-telecaster.jpg",
        },
        {
          id: "bgdsr44",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Prince Three",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption: "Lelatlalala",
          url:
            "https://images.uncyclomedia.co/uncyclopedia/en/thumb/d/df/Purple-Rain-Prince.jpg/400px-Purple-Rain-Prince.jpg",
        },
      ],
    },
    {
      id: 9,
      title: "David Bowie",
      date: "25th April 2014",
      publishDate: "Sep 11 2023",
      content: "Cats and dogs living together",
      editUrl: "editurl",
      isPinned: 0,
      pinnedAt: 0,
      images: [
        {
          id: "j49fda4j38rj",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Bowie One",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption:
            "This is the body content which is very long as i want it to dot dot dot with an eillpsesssese so that i can see it's wokring and then celebrate a job well done",
          url:
            "https://www.simpleminds.com/wp-content/uploads/2016/02/bowie.jpg",
        },
        {
          id: "j49fj38rj",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Bowie Two",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption: "Less writing for the second card",
          url: "http://exclaim.ca/images/up-4bowie.jpg",
        },
        {
          id: "fsdbfht",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Bowie Three",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption: "Less writing for the second card",
          url: "http://img2-ak.lst.fm/i/u/arO/b35700b21cb147e280097ff6ec5e43e7",
        },
      ],
    },
    {
      id: 10,
      title: "John Lennon",
      date: "25th April 2014",
      publishDate: "Sep 11 2023",
      content: "Cats and dogs living together",
      editUrl: "editurl",
      isPinned: 0,
      pinnedAt: 0,
      images: [
        {
          id: "yuthfdj49fda4j38rj",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Lennon One",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption:
            "This is the body content which is very long as i want it to dot dot dot with an eillpsesssese so that i can see it's wokring and then celebrate a job well done",
          url:
            "https://jeracgallero.files.wordpress.com/2014/11/rwflbkf-beatles-john-lennon-1968.png",
        },
        {
          id: "hfmvbcxj49fj38rj",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Lennon Two",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption: "Less writing for the second card",
          url: "http://i.huffpost.com/gen/1397292/images/o-LENNON-facebook.jpg",
        },
        {
          id: "mkyuuffsdbfht",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Lennon Three",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption: "Less writing for the second card",
          url:
            "http://1.bp.blogspot.com/-TCwpncFrx3k/T2dMX1E1Z7I/AAAAAAAACZ8/-_xyg_eUcqE/s1600/john4.jpg",
        },
      ],
    },
    {
      id: 11,
      title: "Nina Simone",
      date: "25th April 2014",
      publishDate: "Sep 11 2023",
      content: "Cats and dogs living together",
      editUrl: "editurl",
      isPinned: 0,
      pinnedAt: 0,
      images: [
        {
          id: "vhfgb-ikj49fda4j38rj",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          width: "800",
          height: "600",
          fileSize: "1024",
          title: "Nina One",
          caption:
            "This is the body content which is very long as i want it to dot dot dot with an eillpsesssese so that i can see it's wokring and then celebrate a job well done",
          url:
            "http://2.bp.blogspot.com/-qL5hamp8aSY/USaKn26zNEI/AAAAAAAAWUQ/fT_rImFdHF4/s640/Nina_Simone_A.JPG",
        },
        {
          id: "j49fk-mm--j38rj",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Nina Two",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption: "Less writing for the second card",
          url:
            "http://blackfilmisbeautiful.com/wp-content/uploads/2012/08/NinaSimone.jpg",
        },
        {
          id: "m-uym-myfsdbfht",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Nina Three",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption: "Less writing for the second card",
          url:
            "https://mondrian.mashable.com/2015%252F09%252F05%252F13%252Fnina.simone.08db6.png%252F950x534.png?signature=YDhB4ty1uJVAm0pjgTeY4SmL3zU=",
        },
      ],
    },
    {
      id: 12,
      title: "Kate Bush",
      date: "25th April 2014",
      content: "Cats and dogs living together",
      editUrl: "editurl",
      isPinned: 0,
      pinnedAt: 0,
      images: [
        {
          id: "jsfg-dsf-49fda4j38rj",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Kate One",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption:
            "This is the body content which is very long as i want it to dot dot dot with an eillpsesssese so that i can see it's wokring and then celebrate a job well done",
          url:
            "https://theappraisaluk.files.wordpress.com/2016/01/kate-bush-2.jpg",
        },
        {
          id: "j4asfsa-=adf-9fj38rj",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Kate Two",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption: "Less writing for the second card",
          url:
            "https://pleasurephoto.files.wordpress.com/2013/11/kate-bush.jpg",
        },
        {
          id: "fsdasdfasd-s-adfbfht",
          guid: "jkd93jds8984jk39399ikdkd",
          type: "jpeg",
          title: "Kate Three",
          width: "800",
          height: "600",
          fileSize: "1024",
          caption: "Less writing for the second card",
          url: "http://i.ebayimg.com/images/i/131560593921-0-1/s-l1000.jpg",
        },
      ],
    },
  ];
});
